a = ["Python", "Exceptions", "try and except"]
print(a[0])
print(a[1])
print(a[2])
print(a[3]) # IndexError: list index out of range
print("end of the code")
print("end of the code") 
print("end of the code") 
print("end of the code") 